<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Ship to multiple address template
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Addresses
 */

 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$idQuote=$cart->getQuote()->getId();

echo "<div id='quoteId' style='display: none'>$idQuote</div>";

echo "<div id='homePath' style='display: none'>".$this->getBaseUrl()."</div>";
?>
<div class="wrapper wrapper_addresses">
    <a class="return-arrow" href="#"></a>
    <p class="heading">Shopping Cart</p>
    <div id="lds-spinner" class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
    <form id="checkout_multishipping_form" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" class="multicheckout address form">
    <input type="hidden" name="continue" value="1" id="can_continue_flag">
    
    <div>
        <div class="basket-list">
            <div class="head">
                <span>Item</span>
                <span>Price</span>
                <span>Quantity</span>
                <span>Address</span>
                <span>Subtotal</span>
            </div>
            <div id="container-items">
                
            </div>
        </div>
        <div class="panel">
            <div class="summary" id="multiShippingSummary">
                
            </div>
        </div>
    </div>
    </form>
</div>

<script>
require(['jquery'], function ($) {
    $(document).on("ready", function(){
        updateMultiShippingCart();
    });
});
</script>
<style>
.lds-spinner {
  position: fixed;
    width: 100%;
    height: 100%;
    left: 0;
    top: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    background: rgba(0,0,0,0.1);
    z-index: 999;
}
.lds-spinner div {
  transform-origin: 32px 32px;
  animation: lds-spinner 1.2s linear infinite;
}
.lds-spinner div:after {
  content: " ";
  display: block;
  position: absolute;
  top: 3px;
  left: 29px;
  width: 5px;
  height: 14px;
  border-radius: 20%;
  background: #fff;
}
.lds-spinner div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.1s;
}
.lds-spinner div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -1s;
}
.lds-spinner div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.9s;
}
.lds-spinner div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.8s;
}
.lds-spinner div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.7s;
}
.lds-spinner div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.6s;
}
.lds-spinner div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.5s;
}
.lds-spinner div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.4s;
}
.lds-spinner div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.3s;
}
.lds-spinner div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.2s;
}
.lds-spinner div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.1s;
}
.lds-spinner div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
}
@keyframes lds-spinner {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
</style>