<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  
$customerAddress = array();
$id=null;
$customerSession = $objectManager->create("Magento\Customer\Model\Session");

if($customerSession->isLoggedIn()){
  $id= $customerSession->getCustomerId();
}
$customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($id);
$GLOBALS['isActive'] = $customerObj['approve_account'];

foreach ($customerObj->getAddresses() as $address)
{
    $customerAddress[] = $address->toArray();
}
$options=null;
foreach ($customerAddress as $customerAddres) {
  $data=$customerAddres['postcode'].' | '.$customerAddres['firstname'].' '.$customerAddres['lastname'].' - '.$customerAddres['company'];
  $options.="<option value='".$customerAddres['entity_id']."'>$data</option>";
}

?>
<!-- SELECT ADRESU -->

<?php if ($id): ?>

<div class="addressSelect">
    <select id='addresses'>
        <?php echo $options; ?>
    </select>
</div>

<?php endif; ?>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$idQuote=$cart->getQuote()->getId();

echo "<div id='quoteId' style='display: none'>$idQuote</div>";

echo "<div id='homePath' style='display: none'>".$this->getBaseUrl()."</div>";


$mediaConfig = $objectManager->get(\Magento\Catalog\Model\Product\Media\Config::class);
$targetDirPath = $mediaConfig->getBaseMediaPath();
echo "<div id='mediaPath' style='display: none'>".$targetDirPath."</div>";
?>




<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?= /* @escapeNotVerified */ $this->getUrl('multishipping/checkout/addresses') ?>"
       data-bind="scope: 'minicart_content'">
       <div class="icon">
           <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="510px" height="510px" viewBox="0 0 510 510" style="enable-background:new 0 0 510 510;" xml:space="preserve">
                <g>
                    <g id="shopping-cart">
                        <path d="M153,408c-28.05,0-51,22.95-51,51s22.95,51,51,51s51-22.95,51-51S181.05,408,153,408z M0,0v51h51l91.8,193.8L107.1,306
                            c-2.55,7.65-5.1,17.85-5.1,25.5c0,28.05,22.95,51,51,51h306v-51H163.2c-2.55,0-5.1-2.55-5.1-5.1v-2.551l22.95-43.35h188.7
                            c20.4,0,35.7-10.2,43.35-25.5L504.9,89.25c5.1-5.1,5.1-7.65,5.1-12.75c0-15.3-10.2-25.5-25.5-25.5H107.1L84.15,0H0z M408,408
                            c-28.05,0-51,22.95-51,51s22.95,51,51,51s51-22.95,51-51S436.05,408,408,408z"></path>
                    </g>
                </g>
            </svg> 
        </div>
        <span class="text"><?= /* @escapeNotVerified */ __('My Cart') ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            
            <span class="counter-label">
                <span><span class="price" id="sidebaritemCost">£0</span>
                <span id="sidebarItemCount">
                    
                </span>
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "0",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" style="display:none !important" data-change="false">
            <!-- tutaj wywoływany jest kontent mini koszyka -->
            
                <div class="block-title">
                    <strong>
                        <span class="text">My Cart</span>
                        <span class="qty" id="contentMiniCartItemCount" title="Items in Cart"></span>
                    </strong>
                </div>
                <div class="block-content">
                    <div class="items-total">
                        <span class="count" id="itemCount"></span>
                        <span>Items in Cart</span>
                    </div>
                    <div class="subtotal">
                        <span class="label">
                        </span>
                        <div class="amount price-container">
                            <span class="price-wrapper" id="itemPrice"><span class="price"></span></span>
                        </div>
                    </div>
                    <div class="actions">
                        <div class="primary">
                            <button id="top-cart-btn-checkout" type="button" class="action primary checkout" data-action="close"
                                title="Proceed to Checkout">Proceed to Checkout</button>
                            <div></div>
                        </div>
                    </div>
                    <strong class="subtitle">Recently added item(s)</strong>
                    <div data-action="scroll" class="minicart-items-wrapper overflowed" style="height: 813px;">
                    <div id="lds-spinner-minicart" class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
                        <ol id="mini-cart" class="minicart-items">
                        
                        </ol>
                    </div>
                    <div class="actions">
                        <div class="secondary">
                            <a class="action viewcart"
                                href="<?php echo $this->getUrl('multishipping/checkout/addresses') ?>">
                                <span>View and Edit Cart</span>
                            </a>
                        </div>
                    </div>
                </div>
             </div>
    <script>
        require(['jquery'], function ($) {
            $(document).on("ready", function(){
                updateProductCart();
                console.log($("#minicart-content-wrapper").parents(".mage-dropdown-dialog"));
                $("#minicart-content-wrapper").parents(".mage-dropdown-dialog").css("height", "0px");
                updateQtyAllItems();
            });

            
        });
    </script>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else: ?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });

            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
        }
    }

    
    </script>
</div>



<style>
.lds-spinner {
    width: 100%;
    height: 100%;
    left: 0;
    top: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    background: rgba(0,0,0,0.1);
    z-index: 999;
}
.lds-spinner div {
  transform-origin: 32px 32px;
  animation: lds-spinner 1.2s linear infinite;
}
.lds-spinner div:after {
  content: " ";
  display: block;
  position: absolute;
  top: 3px;
  left: 29px;
  width: 5px;
  height: 14px;
  border-radius: 20%;
  background: #fff;
}
.lds-spinner div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.1s;
}
.lds-spinner div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -1s;
}
.lds-spinner div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.9s;
}
.lds-spinner div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.8s;
}
.lds-spinner div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.7s;
}
.lds-spinner div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.6s;
}
.lds-spinner div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.5s;
}
.lds-spinner div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.4s;
}
.lds-spinner div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.3s;
}
.lds-spinner div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.2s;
}
.lds-spinner div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.1s;
}
.lds-spinner div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
}
@keyframes lds-spinner {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
</style>