<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
            <input type="number" 
                name="qty" 
                min="0"
                data-changed="false" 
                data-id="product-qty-<?= $_product->getId() ?>" 
                maxlength="12" 
                data-target="product-qty-<?= $_product->getId() ?>" 
                value="<?php
                // GET COUNT IN CART
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
                $items = $cart->getQuote()->getAllItems();
                $count = 0;
                foreach($items as $item) {
                    if($_product->getId() == $item->getProductId()) {
                        $count = $item->getQty();
                        break;
                    }   
                }
                echo $count;
                ?>" 
                title="<?= /* @escapeNotVerified */ __('Qty') ?>" 
                class="input-text qty inputProductQty"/>

                <button type="button" 
                data-target="product-qty-<?= $_product->getId() ?>" 
                data-action="+" 
                class="increaseQty">+</button>
                <button type="button" 
                data-target="product-qty-<?= $_product->getId() ?>" 
                data-action="-" 
                class="decreaseQty">-</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button data-id="addToCart_product-qty-<?= $_product->getId() ?>" type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"
                    style="display: none">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
