<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- <?= /* @escapeNotVerified */ $block->getMiscellaneousHtml();?> -->

  <section id="see_all_products">
        <div class="wrapper">
            <div class="offset-lg-5"></div>
            <p>Are you searching for different products? See them all!</p>
            <div class="btn-box">
                <a class="btn btn-green" href="./product_list.html">ALL PRODUCTS</a>
            </div>
        </div>
    </section>
    <footer class="footer">
        <div class="wrapper">
            <div class="column">
                <p class="column-title">CUSTOMER SERVICE</p>
                <ul>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">FAQs</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Capital On Tap</a></li>
                </ul>
            </div>
            <div class="column">
                <p class="column-title">THE SMALL PRINT</p>
                <ul>
                    <li><a href="#">Deliveries</a></li>
                    <li><a href="#">Terms & Conditions</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Site Map</a></li>
                </ul>
            </div>
            <div class="about">
                <div class="img">
                    <img src="./assets/img/logo_2.png" alt="">
                </div>
                <p>Diamonds & Pearl Trading Ltd. Cromwell Industrial Estate, Unit 43, Staffa Rd, Leyton E10 7QZ | Copyright© 2019</p>
            </div>
            <div class="contact">
                <p>Have any questions? Contact us</p>
                <p class="number">(+44) 01277 219818</p>
                <p class="number">(+44) 07886 076847</p>
            </div>
        </div>
    </footer>
