<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- <?= /* @escapeNotVerified */ $block->getMiscellaneousHtml();?> -->
 
    <footer class="footer">
        <div class="wrapper">
            <div class="column">
                <p class="column-title">CUSTOMER SERVICE</p>
                <ul>
                    <li><a href="<?php echo $this->getUrl('about-us') ?>">About Us</a></li>
                    <li><a href="<?php echo $this->getUrl('faq') ?>">FAQs</a></li>
                    <li><a href="<?php echo $this->getUrl('contact') ?>">Contact Us</a></li>
                    <li><a href="<?php echo $this->getUrl('capital-on-tap') ?>">Capital On Tap</a></li>
                </ul>
            </div>
            <div class="column">
                <p class="column-title">THE SMALL PRINT</p>
                <ul>
                    <li><a href="<?php echo $this->getUrl('deliveries') ?>">Deliveries</a></li>
                    <li><a href="<?php echo $this->getUrl('terms-conditions') ?>">Terms & Conditions</a></li>
                    <li><a href="<?php echo $this->getUrl('privacy') ?>">Privacy</a></li>
                    <li><a href="<?php echo $this->getUrl('site-map') ?>">Site Map</a></li>
                </ul>
            </div>
            <div class="about">
                <div class="img">
                    <img src="./assets/img/logo_2.png" alt="">
                </div>
                <p>Diamonds & Pearl Trading Ltd. Cromwell Industrial Estate, Unit 43, Staffa Rd, Leyton E10 7QZ | Copyright© 2019</p>
            </div>
            <div class="contact">
                <p>Have any questions? Contact us</p>
                <p class="number">(+44) 01277 219818</p>
                <p class="number">(+44) 07886 076847</p>
            </div>
        </div>
    </footer>
