<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<section id="see_all_products">
    <div class="wrapper">
        <div class="offset-lg-5"></div>
        <p>Are you searching for different products? See them all!</p>
        <div class="btn-box">
            <a class="btn btn-green" href="<?php echo $this->getUrl('all-products.html') ?>">ALL PRODUCTS</a>
        </div>
    </div>
</section>
