<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 ?>
    <section id="faq">
        <div class="wrapper">
            <h1>Faq</h1>
            <div class="faq-table">
                <div class="question collapsed">
                    <div class="heading">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </span>
                        <span>
                            <button class="collapse-btn"></button>
                        </span>
                    </div>
                    <div class="text">
                        <p>
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                        </p>
                    </div>
                </div>
                <div class="question collapsed">
                    <div class="heading">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </span>
                        <span>
                            <button class="collapse-btn"></button>
                        </span>
                    </div>
                    <div class="text">
                        <p>
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                        </p>
                    </div>
                </div>
                <div class="question collapsed">
                    <div class="heading">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </span>
                        <span>
                            <button class="collapse-btn"></button>
                        </span>
                    </div>
                    <div class="text">
                        <p>
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                        </p>
                    </div>
                </div>
                <div class="question collapsed">
                    <div class="heading">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </span>
                        <span>
                            <button class="collapse-btn"></button>
                        </span>
                    </div>
                    <div class="text">
                        <p>
                            Cras ornare lacus leo, quis commodo turpis commodo ut. Suspendisse iaculis fermentum sem, vel vehicula leo sagittis non. Aliquam id massa id arcu varius mollis. Mauris eget congue eros, eu sollicitudin nisl. Sed et arcu vel velit maximus porta scelerisque vel nulla. Nulla sit amet volutpat libero. Integer efficitur dui vitae ex molestie, nec tempor neque fringilla. Sed dictum lectus nibh, sed imperdiet odio tempus et. Cras molestie felis at libero consectetur hendrerit.
                        </p>
                    </div>
                </div>
            </div>            
        </div>
    </section>