
<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

 /*
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  
$customerAddress = array();
$id=null;
$customerSession = $objectManager->create("Magento\Customer\Model\Session");

if($customerSession->isLoggedIn()){
  $id= $customerSession->getCustomerId();
}
$customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($id);
$GLOBALS['isActive'] = $customerObj['approve_account'];

foreach ($customerObj->getAddresses() as $address)
{
    $customerAddress[] = $address->toArray();
}
$options=null;
foreach ($customerAddress as $customerAddres) {
  $data=$customerAddres['postcode'].' | '.$customerAddres['firstname'].' '.$customerAddres['lastname'].' - '.$customerAddres['company'];
  $options.="<option value='".$customerAddres['entity_id']."'>$data</option>";
}*/
 ?>

 
 <!--

    Dodatkowe divy dla headera

  -->
<!--
<?php //if ($id && $options): ?>
<li>
<select id='addresses'>
<?php //echo $options; ?>
</select> 
</li>
-->

<?php //endif; ?>


