<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<!--

    ---Your code here---

-->
<section id="contact">
    <div class="wrapper">
        <div id="contact-info">
            <div class="left">
                <p class="heading">Contact information</p>
                <div class="contact-logo">
                    <span>DIAMONDS & PEARL TRADING LTD.</span>
                </div>
                <div class="info">
                    <p>Address:</p>
                    <p>Unit 43</p>
                    <p>Cromwell Industrial Estate</p>
                    <p>Staffa Rd  |  Leyton</p>
                    <p>E10 7QZ</p>
                </div>
                <p class="bottom-text">Company registered in England No. 9274200  |  Vat reg. No. 198361957</p>
            </div>
            <div class="right">
                <div>
                    <span>(+44) 01277 219818</span>
                </div>
                <div>
                    <span>(+44) 07886 076847</span>
                </div>
                <div>
                    <span>radler@radleruk.com</span>
                </div>
            </div>
        </div>
        <div id="map">
        </div>
    </div>
</section>
<section id="contact_form">
    <div class="wrapper">
        <div class="text">
                <p class="heading">
                    Have any questions?
                    Send us a message
                </p>
                <p class="bottom-text">Leave us your contact or write us some message</p>
        </div>
        <form class="form contact"
              action="<?= $block->escapeUrl($block->getFormAction()) ?>"
              id="contact-form"
              method="post"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="left">
                        <div class="field name required">
                            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                            </div>
                        </div>
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                    </div>
                    <div class="field telephone">
                        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                        <div class="control">
                            <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                        </div>
                    </div>
                </div>
                <div class="right">
                    <div class="field comment required">
                        <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
                        <div class="control">
                            <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                        </div>
                    </div>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</section>