<?php /** @var \RLTSquare\BestSeller\Block\Product\GridProduct $block */ ?>
<?php if ($block->isEnableDisable() && $block->getCurrentPagePath()): ?>
    <?php $collection = $block->getCollection();
    $list_product = $block->getListProduct();
    $iterator = 1;
    $image = 'category_page_grid';
    $pos = $list_product->getPositioned();
    $_helper = $block->getCatalogHelper();
    $config = $list_product->getWidgetCfg();
    $showCart = 1;
    $showCompare = 0;
    $showWishlist = 1;
    $showReview = 1;
    $viewMode = 'grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <?php if ($collection->getData()): ?>
        <div class="products wrapper most_viewed-wrapper custom_grid-wrapper content-products">
            <?php $iterator = 1; ?>
            <div class="block-title">
                <strong>Our bestsellers</strong>
            </div>
            <ol class="products list items product-items">
                <?php foreach ($collection->getData() as $data) { ?>
                    <?php $product_id = $data['product_id']; ?>
                    <?php $_product = $block->getLoadProduct($product_id); ?>
                    <?php if (isset($_product)): ?>
                        <?php if ($_product->getID()): ?>
                            <?php /* @escapeNotVerified */ ?>
                            <?php echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item ">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php $productImage = $list_product->getImage($_product, $image); ?>
                                <?php if ($pos != null): ?>
                                    <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                                <?php endif; ?>
                                <div class="images-container">
                                    <?php $_productNameStripped = $list_product->stripTags($_product->getName(), null, true); ?>
                                        <a href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                           tabindex="-1">
                                            <?php echo $block->getLazyLoadedImage($productImage) ?>
                                        </a>
                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <?php if ($showCart): ?>
                                                    <div class="product-item-actions">
                                                            <?php if ($_product->isSaleable()): ?>
                                                                <?php $postParams = $list_product->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                      action="<?php echo $postParams['action']; ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?php echo $postParams['data']['product']; ?>">
                                                                    <input type="hidden"
                                                                           name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                           value="<?php echo $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                    <?php echo $list_product->getBlockHtml('formkey') ?>
                                                                    
                                                                    <div class="control">
                                                                        <input type="number" 
                                                                            name="qty" 
                                                                            id="Our-bestsellers-qty<?= /* @escapeNotVerified */ $_product->getId() ?>" 
                                                                            maxlength="12" 
                                                                            value="1" 
                                                                            title="<?= /* @escapeNotVerified */ __('Qty') ?>" 
                                                                            class="input-text qty"/>

                                                                        <button type="button"  id="Our-bestsellers-qty<?= /* @escapeNotVerified */ $_product->getId() ?>-upt" class="increaseQty">+</button>
                                                                        <button type="button"  id="Our-bestsellers-qty<?= /* @escapeNotVerified */ $_product->getId() ?>-dec"  class="decreaseQty">-</button>
                                                                    </div>
                                                                                                                                                                                  
                                                                    <button type="submit"
                                                                            title="<?php echo $list_product->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary button btn-cart">
                                                                <span class="tooltip"><?php echo __('Add to Cart') ?>
                                                                </span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                            echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                            echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                           
                                        <?php endif; ?>
                                    <div class="product-item-details">
                                        <?php echo $list_product->getProductPrice($_product) ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div data-role="add-to-links"
                                                 class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       class="action towishlist alotheme-tooltip"
                                                       title="<?php echo $list_product->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $list_product->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $list_product->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <i class="fa fa-heart icon icons"></i>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <h4 class="product-item-name">
                                            <strong class="product-item-link">
                                                <a class="product-item-link"
                                                href="<?php /* @escapeNotVerified */
                                                echo $_product->getProductUrl() ?>"
                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                    <?php /* @escapeNotVerified */
                                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                </a>
                                            </strong>
                                        </h4>
                                        <?php echo $showReview ? $list_product->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php } ?>
            </ol>
        </div>
    <?php endif; ?>
<?php endif; ?>