<?php /** @var \RLTSquare\BestSeller\Block\Product\GridProduct $block */ ?>
<?php if ($block->isEnableDisable() && $block->getCurrentPagePath()): ?>
    <?php $collection = $block->getCollection();
    $list_product = $block->getListProduct();
    $iterator = 1;
    $image = 'category_page_grid';
    $pos = $list_product->getPositioned();
    $_helper = $block->getCatalogHelper();
    $config = $list_product->getWidgetCfg();
    $showCart = 1;
    $showCompare = 0;
    $showWishlist = 1;
    $showReview = 1;
    $viewMode = 'grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <?php if ($collection->getData()): ?>
        <div class="products wrapper most_viewed-wrapper custom_grid-wrapper content-products">
            <?php $iterator = 1; ?>
            <div class="block-title">
                <strong>Our bestsellers</strong>
            </div>
            <ol class="products list items product-items">
                <?php foreach ($collection->getData() as $data) { ?>
                    <?php $product_id = $data['product_id']; ?>
                    <?php $_product = $block->getLoadProduct($product_id); ?>
                    <?php if (isset($_product)): ?>
                        <?php if ($_product->getID()): ?>
                            <?php /* @escapeNotVerified */ ?>
                            <?php echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php $productImage = $list_product->getImage($_product, $image); ?>
                                <?php if ($pos != null): ?>
                                    <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                                <?php endif; ?>
                                <?php $_productNameStripped = $list_product->stripTags($_product->getName(), null, true); ?>
                                        <a href="<?php /* @escapeNotVerified */
                                            echo $_product->getProductUrl() ?>" class="product-item-photo"
                                           tabindex="-1">
                                            <?php echo $block->getLazyLoadedImage($productImage) ?>
                                        </a>
                                <div class="product-item-details">
                                            <strong class="product-item-name">
                                                <a class="product-item-link"
                                                href="<?php /* @escapeNotVerified */
                                                echo $_product->getProductUrl() ?>"
                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                    <?php /* @escapeNotVerified */
                                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                </a>
                                            </strong>

                                            <?php
                                    $size = $_product->getResource()->getAttribute('size')->getFrontend()->getValue($_product);
                                    $alcoholByVolume = $_product->getResource()->getAttribute('alcohol_by_volume')->getFrontend()->getValue($_product);
                                    $isReturnable = $_product->getResource()->getAttribute('returnable_bottle')->getFrontend()->getValue($_product);
                                ?>
                                <div class="attribute-short">
                                    <?php echo $size; ?>
                                    <?php echo $alcoholByVolume; ?>
                                    <?php echo ($isReturnable == "Yes" ? "" : "NRB"); ?>       
                                </div>
                                        <?php echo $list_product->getProductPrice($_product) ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       class="action towishlist alotheme-tooltip"
                                                       title="<?php echo $list_product->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $list_product->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $list_product->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <i class="fa fa-heart icon icons"></i>
                                                    </a>
                                                <?php endif; ?>
                                        
                                        <?php endif; ?>
                                        <?php echo $showReview ? $list_product->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                    </div>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <?php if ($showCart): ?>
                                                    <div class="product-item-actions">
                                                            <?php if ($_product->isSaleable() && $GLOBALS['isActive']==2 ): ?>
                                                                <?php $postParams = $list_product->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                      action="<?php echo $postParams['action']; ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?php echo $postParams['data']['product']; ?>">
                                                                    <input type="hidden"
                                                                           name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                           value="<?php echo $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                    <?php echo $list_product->getBlockHtml('formkey') ?>
                                                                    
                                                                    <div class="control">
                                                                <input type="number" 
                                                                    name="qty" 
                                                                    data-id="product-qty-<?= $_product->getId() ?>" 
                                                                    maxlength="12" 
                                                                    data-target="product-qty-<?= $_product->getId() ?>" 
                                                                    value="<?php
                                                                    // GET COUNT IN CART
                                                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                                                    $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
                                                                    $items = $cart->getQuote()->getAllItems();
                                                                    $count = 0;
                                                                    foreach($items as $item) {
                                                                        if($_product->getId() == $item->getProductId()) {
                                                                            $count = $item->getQty();
                                                                            break;
                                                                        }   
                                                                    }
                                                                    echo $count;
                                                                    ?>" 
                                                                    min="0" 
                                                                    data-changed="false" 
                                                                    title="<?= /* @escapeNotVerified */ __('Qty') ?>" 
                                                                    class="input-text qty inputProductQty"/>

                                                                    <button type="button" 
                                                                    data-target="product-qty-<?= $_product->getId() ?>" 
                                                                    data-action="+" 
                                                                    class="increaseQty">+</button>
                                                                    <button type="button" 
                                                                    data-target="product-qty-<?= $_product->getId() ?>" 
                                                                    data-action="-" 
                                                                    class="decreaseQty">-</button>
                                                            </div>
                                                                                                                                                                                  
                                                                    <button type="submit" data-id="addToCart_product-qty-<?= $_product->getId() ?>"
                                                                            title="<?php echo $list_product->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary button btn-cart">
                                                                <span class="tooltip"><?php echo __('Add to Cart') ?>
                                                                </span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                            echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                            echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                           
                                        <?php endif; ?>
                                </div>
                            </div>
                            <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php } ?>
            </ol>
        </div>
    <?php endif; ?>
<?php endif; ?>