<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <p>
        <div class="field customer_documents ">
            <label for="customer_documents" class="label">
                <span><?php /* @escapeNotVerified */echo __('Required Documents (.e.g. XYZ XYZ XYZ)') ?></span>
            </label>
            <div class="control">
                <input type="file" 
                    name="customer_documents" 
                    id="customer_documents" 
                    title="<?php /* @escapeNotVerified */ echo __('Required Documents') ?>" 
                    class="input-text" 
                    data-validate="{required:true}">
            </div>
        </div>
    </p>
</fieldset>